console.log("hello world".replace("world","universe"))
console.log("foo bar baz".replaceAll("bar", "baz"));
console.log("Hello".charAt(4));
console.log("Hello World".charAt(-1));
console.log("Hello".at(-1)); 
console.log("Hello World".length); 
console.log("JavaScript".slice(4, 10)); 
console.log("JavaScript".slice(-6)); 
console.log("JavaScript".substring(4, 10));
console.log("Hello".substring(-2)); 
console.log("Hello".charCodeAt(1));
console.log("Hello".toUpperCase()); 
console.log("Hello World".split(" ")); 
console.log("a,b,c".split(",")); 
console.log("abcabcabc".split("a", 2)); 
console.log("JavaScript is fun".indexOf("is"));
console.log("JavaScript".slice(-4, -1)); 
console.log("123456789".substr(3, 4)); 
console.log("JavaScript".startsWith("Java")); 
console.log("JavaScript".endsWith("Script")); 
console.log("  Hello ".trim());
console.log("abcDEF".toLowerCase());  
console.log("Hello".concat(" ", "World"));
console.log("Hello"[0]);
console.log("Hello".charAt(10));
console.log("Hello World".includes("World"));
console.log("Hello".repeat(3));  
 console.log("abc123".search(/[0-9]/));   
 console.log("   ".trim().length); 
 console.log("JavaScript".replace("Script", "Fun"));
 console.log("Hello".padStart(10, "*")); 
 console.log("Hello".padEnd(10, "!"));
 console.log("JavaScript is cool".lastIndexOf("is")); 
 console.log("Test123".startsWith("T", 1));
 console.log("Test123".endsWith("3", 6)); 
 console.log("JavaScript".slice(4, -2));
 console.log("abcdef".split("", 3));  
 console.log("  spaced out ".trimStart()); 
 console.log("repeat".repeat(0)); 
 console.log("12345".indexOf("6"));  
